# Generated by Django 4.1 on 2025-01-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_typeofservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goog',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
