# Generated by Django 4.2 on 2025-02-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_goog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_of_service', to='myapp.typeofservice', verbose_name='Услуга'),
        ),
    ]
