# Generated by Django 4.2 on 2025-02-02 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_orders_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_service', to='myapp.typeofservice', verbose_name='Услуга'),
        ),
    ]
